services:
    nginx:
        working_dir: /var/www
        build:
           context: ./nginx
           dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        ports:
            - ${NGINX_PORT_HTTP}:80
        volumes:
            - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
            - ${NGINX_LOG_DIR}:/var/log/nginx
            - ${APPLICATION_PATH}:/var/www
